apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-api-deployment
spec:
  selector:
    matchLabels:
      app: feed-api
  replicas: 2
  template:
    metadata:
      labels:
        app: feed-api
    spec:
      containers:
        - name: feed-api
          imagePullPolicy: Always
          image: dilipagheda/udagram-feed-api
          ports:
            - containerPort: 8080
          env:
            - name: URL
              value: http://localhost:8100
            - name: AWS_BUCKET
              value: udagramaghedadev
            - name: AWS_REGION
              value: ap-southeast-2
            - name: AWS_PROFILE
              value: default
            - name: POSTGRES_HOST
              value: udagramdb.cpqmop69dv8r.ap-southeast-2.rds.amazonaws.com
            - name: POSTGRES_DB
              value: udagramdb
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: udagramsecret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: udagramsecret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: udagramsecret
                  key: JWT_SECRET
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: udagramawssecret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: udagramawssecret
                  key: AWS_SECRET_ACCESS_KEY
