apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-api-deployment
spec:
  selector:
    matchLabels:
      app: feed-api
  replicas: 1
  template:
    metadata:
      labels:
        app: feed-api
    spec:
      containers:
        - name: feed-api
          image: dilipagheda/udagram-feed-api:latest
          ports:
            - containerPort: 8080
