apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dilipagheda/udagram-frontend:latest
          ports:
            - containerPort: 8100
          env:
            - name: URL
              value: http://localhost:8100
            - name: AWS_BUCKET
              value: udagramaghedadev
            - name: AWS_REGION
              value: ap-southeast-2
            - name: AWS_PROFILE
              value: default
            - name: POSTGRES_HOST
              value: udagramdb.cpqmop69dv8r.ap-southeast-2.rds.amazonaws.com
            - name: POSTGRES_DB
              value: udagramdb
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: udagramsecret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: udagramsecret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: udagramsecret
                  key: JWT_SECRET