apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
spec:
  selector:
    matchLabels:
      app: user-api
  replicas: 1
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: dilipagheda/udagram-user-api:latest
          ports:
            - containerPort: 8080
